# Generated by Django 4.2.4 on 2024-01-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('target_name', models.CharField(max_length=50)),
                ('target_des', models.CharField(max_length=50)),
            ],
        ),
    ]
